# Generated by Django 3.2.3 on 2021-05-28 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20210527_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advocates',
        ),
    ]
