# Generated by Django 3.2.3 on 2021-05-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_delete_advocates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advocates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
