# Generated by Django 3.2.3 on 2021-06-01 05:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_advocates'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocates',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
