# Generated by Django 3.2.3 on 2021-06-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_advocates_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocates',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
