# Generated by Django 3.2.3 on 2021-06-06 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactUs',
        ),
    ]
