# Generated by Django 3.2.3 on 2021-06-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_rename_contact_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Mobile',
            field=models.CharField(max_length=20),
        ),
    ]
