# Generated by Django 3.2.3 on 2021-07-13 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrologers',
            name='image',
            field=models.ImageField(default=False, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='automobilerepair',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bakeries',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banks',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books_stationaries',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='builders',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ca',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carpenters',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catering',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloths',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computers',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courier',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drivers',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drycleaners',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electricians',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electronics',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image'),
            preserve_default=False,
        ),
    ]
